apiVersion: memsql.com/v1alpha1
kind: MemsqlCluster
metadata:
  name: sdb-cluster
spec:
  license: "BDk3MGQ4YWM5NDU4MTRlYjBiYTE4ZjU4MGRjZTM5MWFjAAAAAAAAAAAEAAAAAAAAACgwNgIZALEr4i6wO7uOXP4oEDBYmoGCH3SvJ8TsOwIZANi9WYwU9rzrqCHyhPsqZynvl1z91+WtWg=="
  adminHashedPassword: "*9177CC8207174BDBB5ED66B2140C75171283F15D"
 # containers:
 #   - name: sdb-operator
 #     image: singlestore/node



  nodeImage:
    repository: singlestore/node
    tag: alma-7.8.17-69cee1f1a3    #singlestore/node:latest

  redundancyLevel: 2

  serviceSpec:
     objectMetaOverrides:
      labels:
        custom: label
      annotations:
        custom: annotations

  aggregatorSpec:
    count: 1
    height: 0.5
    storageGB: 50
    storageClass: standard

    objectMetaOverrides:
      annotations:
        optional: annotation
      labels:
        optional: label

  leafSpec:
    count: 1
    height: 0.5
    storageGB: 50
    storageClass: standard

    objectMetaOverrides:
      annotations:
        optional: annotation
      labels:
        optional: label

  serviceSpec:
    type: "LoadBalancer"
